RAW_COMMENTS_BUCKET = "reddit-comments-raw"
CLEAN_COMMENTS_BUCKET = "reddit-comments-clean"
RAW_SUBMISSIONS_BUCKET = "reddit-submissions-raw"
CLEAN_SUBMISSIONS_BUCKET = "reddit-submissions-clean"
OUTPUT_DIRECTORY = "./Data"
